import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const nodes=new Map();
const node=selector=>{if(!nodes.has(selector))nodes.set(selector,{innerHTML:'',textContent:'',value:'',style:{},dataset:{},classList:{toggle(){},add(){},remove(){}},addEventListener(k,f){this[k]=f},querySelector(){return node('child')},showModal(){}});return nodes.get(selector);};
const storage=new Map();
const context={console,Math:Object.create(Math),Date,JSON,Promise,Number,Object,Array,Set,String,Boolean,document:{querySelector:node,querySelectorAll:()=>[],createElement:()=>node('div'),body:{dataset:{}}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},sessionStorage:{getItem:()=>null,setItem(){}},location:{hash:''},history:{replaceState(){}},navigator:{},requestAnimationFrame:f=>f(),setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},confirm:()=>true};
context.window=context;context.addEventListener=()=>{};
let source=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');
source=source.replace('  bindStaticControls();\n  render();\n  registerWebMCP();',`globalThis.test={get state(){return state},set state(v){state=v},set mode(v){viewMode=v},defaultState,STAGES,SUPPORT_CANCELS,ABILITY_CANCELS,TAG_DESCRIPTIONS,selectionCancelledTags,cancelledTags,effectiveStageDc,beginPlayerTurn,resolveSupport,resolveDrive,applyGroundFailure,prepareCollisionChecks,resolveRuleCheck,render,renderChoice,courseManeuver,masterActionOptions,executeMasterAction,renderCanonPending,raceTags,canAegonCutoff};`);
vm.runInNewContext(source,context);const t=context.test;
function fresh(index=0){t.state=t.defaultState();t.state.started=true;t.state.stageIndex=index;t.state.phase='choice';t.state.masterTurnStage=index;t.state.masterTurnOrder=['aegon','saira','pello','mael','ordis'];t.state.selection.arc=t.STAGES[index].arcs[0];return t.state;}

context.Math.random=()=>0.5;
let state=fresh();state.phase='rivals';t.mode='master';state.masterTurnOrder=['aegon','saira','pello','mael','ordis'];state.masterTurnStage=0;
state.rivalCharges.aegon.star=true;
assert.equal(t.masterActionOptions('aegon').find(a=>a.id==='aegon_hunt').dc,18);
state.rivalCharges.aegon.wing=true;const angle=t.masterActionOptions('aegon').find(a=>a.id==='aegon_angle');assert.equal(angle.dc,9);t.executeMasterAction('aegon',angle,{raw:12,total:19});assert.equal(t.cancelledTags('aegon').length,2);assert.equal(state.unblockable.aegon,0);
state=fresh();state.phase='rivals';state.masterAction='pello_swap';state.distance.pello=0;state.distance.aegon=3;state.canonTarget='aegon';state.rivalCharges.pello.sword=true;assert.equal(t.masterActionOptions('pello').find(a=>a.id==='pello_swap').dc,17);
state.rivalCharges.pello.wing=true;const exit=t.masterActionOptions('pello').find(a=>a.id==='pello_clear_exit');assert(exit.automatic);t.executeMasterAction('pello',exit,{raw:15,total:exit.dc,automatic:true});assert.equal(state.distance.pello,2);assert.equal(state.rivalCharges.pello.wing,false);assert.equal(state.unblockable.pello,0);
state=fresh();state.phase='rivals';state.rivalCharges.pello.star=true;const teleport=t.masterActionOptions('pello').find(a=>a.id==='pello_teleport');assert.equal(teleport.dc,16);t.executeMasterAction('pello',teleport,{raw:1,total:8});assert.equal(state.rivalUsage.pelloTeleports.length,1);assert.equal(state.rivalCharges.pello.star,false);assert(!state.stageFailures.includes('pello'),'No additional obstacle damage on failed teleport');
state=fresh();state.phase='rivals';state.rivalUsage.sairaHeat=3;state.rivalCharges.saira.star=true;let dash=t.masterActionOptions('saira').find(a=>a.id==='saira_dash');assert.equal(dash.dc,18);t.executeMasterAction('saira',dash,{raw:16,total:22,canonDecided:true});assert.equal(state.distance.saira,4);assert.equal(state.rivalUsage.sairaHeat,1);
state=fresh();state.phase='rivals';state.rivalUsage.sairaHeat=3;state.rivalCharges.saira.wing=true;let up=t.masterActionOptions('saira').find(a=>a.id==='saira_updraft');t.executeMasterAction('saira',up,{raw:4,total:10});assert(state.canonPending);assert(state.rivalCharges.saira.wing,'Resource held before decision');assert.equal(state.rivalIntegrity.saira,32,'Damage held before decision');node('#canonBoost').click();assert.equal(state.rivalUsage.sairaHeat,1);assert.equal(state.rivalCharges.saira.wing,false);assert(state.masterLastResult.success);
state=fresh();state.phase='rivals';state.rivalUsage.sairaHeat=2;let course=t.masterActionOptions('saira').find(a=>a.id==='saira_course');assert.equal(course.bonus,3);t.executeMasterAction('saira',course,{raw:2,total:5});assert(state.canonPending);node('#canonReroll').click();assert.equal(state.rivalUsage.sairaHeat,3,'Spend one then gain rolled heat after success');
state=fresh();state.phase='rivals';state.distance.saira=5;state.distance.aegon=10;state.distance.pello=1;state.rivalUsage.sairaHeat=1;state.rivalCharges.saira.sword=true;let veil=t.masterActionOptions('saira').find(a=>a.id==='saira_veil');assert(veil.automatic);context.Math.random=()=>0;t.executeMasterAction('saira',veil,{raw:15,total:15});assert.equal(state.npcHp.pello,43);assert(state.npcTags.pello.heat);assert.equal(state.rivalIntegrity.pello,24,'Direct pilot damage does not damage chariot');
state=fresh();state.phase='rivals';state.masterTurnOrder=['pello','aegon'];state.masterTurnIndex=0;state.masterAction='pello_laugh';state.canonTarget='aegon';const laugh=t.masterActionOptions('pello').find(a=>a.id==='pello_laugh');t.executeMasterAction('pello',laugh,{raw:15,total:15});assert.equal(state.skipStages.aegon,0);assert.equal(state.npcHp.aegon,65);
console.log('PASS: canonical DCs, selectable targets, automatic clear exit, teleport limit, distinct pilot damage, heat decisions before mutations, reroll/boost spending, rear-target saves and laugh skip.');
