import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const nodes=new Map(),storage=new Map();const node=k=>{if(!nodes.has(k))nodes.set(k,{innerHTML:'',textContent:'',value:0,style:{},dataset:{},classList:{toggle(){},add(){},remove(){}},events:{},addEventListener(k,f){this.events[k]=f},querySelector(){return node('child')},showModal(){},before(){},append(){}});return nodes.get(k)};
const c={console,Math,Date,JSON,Promise,Number,Object,Array,Set,String,Boolean,document:{querySelector:node,querySelectorAll:()=>[],createElement:()=>node('div'),body:{dataset:{}}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},sessionStorage:{getItem:()=>null,setItem(){}},location:{hash:''},history:{replaceState(){}},navigator:{},requestAnimationFrame:f=>f(),setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},confirm:()=>true};c.window=c;c.addEventListener=()=>{};vm.createContext(c);
for(const f of ['crew-seed.js','crew.js'])vm.runInContext(fs.readFileSync(new URL('../dist/'+f,import.meta.url),'utf8'),c);
const actor=c.SapphireCrew.seed;assert.equal(actor.name,'Анвида Железная');assert.equal(actor.hpMax,37);assert.equal(actor.ac,18);assert.equal(actor.prof,3);assert.equal(actor.tools.land.bonus,2);assert.equal(actor.skills.ani.bonus,3);assert.equal(actor.skills.inv.bonus,7);assert.equal(actor.abilities.dex.save,2);assert.equal(actor.abilities.wis.save,0);assert.equal(actor.abilities.int.save,7);assert.equal(actor.ranged[0].bonus,8);assert.equal(actor.ranged[0].damageBonus,5);assert(!actor.ranged[0].loading);assert(actor.ranged[0].ammoGenerated);assert.equal(actor.portrait,null,'Relative Foundry asset path does not pretend to be an available picture');assert.throws(()=>c.SapphireCrew.formula('alert(1)'));assert.throws(()=>c.SapphireCrew.normalize({name:'invalid'}));
const source=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8').replace('  bindStaticControls();\n  render();\n  registerWebMCP();','globalThis.t={get state(){return state},set state(v){state=v},defaultState,ensureCrew,crewActor,crewCheck,saveRosterActor,renderSetup,renderChoice,renderSupportRoll,renderDriveRoll,beginPlayerTurn,resolveHelper,resolveHelperShot,helperTargets,damageCrew,applyDamage,chooseRoadLane,commitRoadLane,resolveDrive,sceneCue,ensureDistanceState};');vm.runInContext(source,c);const t=c.t;
function fresh(){t.state=t.defaultState();t.ensureCrew();t.state.selection.arc='shield';return t.state;}
let s=fresh();assert.equal(s.controlBonus,2);assert.equal(t.crewCheck('driver','calm').bonus,3);assert.equal(t.crewCheck('driver','scout').bonus,7);assert.equal(t.crewCheck('driver','guard').bonus,4);assert.equal(t.crewCheck('driver','repair').bonus,7);t.renderSetup();assert(nodes.get('#playArea').innerHTML.includes('Анвида Железная'));assert(nodes.get('#playArea').innerHTML.includes('Пустое место'));
const helper=JSON.parse(JSON.stringify(actor));helper.id='test-helper';helper.name='Помощник';helper.skills.ani.bonus=9;helper.hp=20;helper.hpMax=20;t.saveRosterActor(helper);s.crew.helper=helper.id;t.ensureCrew();assert.equal(t.crewCheck('helper','calm').bonus,9);assert.equal(t.crewCheck('driver','calm').bonus,3);s.helperAction='calm';s.started=true;t.beginPlayerTurn();assert.equal(s.phase,'helper');t.resolveHelper({raw:10,total:19},14);assert.equal(s.phase,'support');assert.equal(s.supportControlBonus,2);
s=fresh();s.crew.helper=helper.id;t.ensureCrew();s.helperAction='ram';s.started=true;const old=JSON.stringify(s.distance);t.resolveHelper({raw:20,total:99},10);assert.equal(JSON.stringify(s.distance),old,'Assistant cannot ram even with a forged selection');
s=fresh();t.damageCrew('driver',10,'poison');assert.equal(s.crew.hp[actor.id],32,'Resistance comes from sheet');assert.equal(s.integrity,30,'Personal damage never damages chariot');s.crewProtected=true;t.damageCrew('driver',100,'fire');assert.equal(s.crew.hp[actor.id],32,'Runes protect personal damage');t.applyDamage(9,{crew:true});assert.equal(s.integrity,23);assert.equal(s.crew.hp[actor.id],30,'Danger damage is split instead of duplicating it');
s=fresh();s.started=true;s.distance.player=10;s.distance.aegon=10;s.roadLanes.player=0;s.roadLanes.aegon=1;s.crew.helper=helper.id;t.ensureCrew();assert(t.helperTargets().includes('aegon'));s.distance.aegon=11;assert(!t.helperTargets().includes('aegon'));s.distance.aegon=10;s.roadLanes.aegon=3;assert(!t.helperTargets().includes('aegon'));
s=fresh();s.started=true;s.crew.helper=helper.id;t.ensureCrew();s.phase='helper';s.helperAction='ranged';s.helperWeapon=helper.ranged[0].id;s.helperTarget='aegon';s.roadLanes.player=0;s.roadLanes.aegon=1;const bullet=s.crew.ammo[helper.id+':'+s.helperWeapon];t.resolveHelperShot({raw:20,total:28});assert.equal(s.phase,'helper','Extra Attack preserves the second shot');assert.equal(s.helperShots,1);t.resolveHelperShot({raw:20,total:28});assert.equal(s.phase,'support','Action ends after two attacks');assert.equal(s.crew.ammo[helper.id+':'+s.helperWeapon],bullet,'Repeating Shot generates ammunition');
s=fresh();s.started=true;s.phase='choice';t.chooseRoadLane('player',4);assert.equal(s.roadLanes.player,0);assert.equal(s.lastCueRoadLanes.player,0);assert.equal(s.selection.arc,'star');t.sceneCue('player','scout','Support');assert.equal(s.sceneEvents.at(-1).afterRoadLanes.player,0);t.resolveDrive({raw:18,total:30});assert.equal(s.roadLanes.player,4);assert.equal(s.sceneEvents.at(-1).beforeRoadLanes.player,0);assert.equal(s.sceneEvents.at(-1).afterRoadLanes.player,4);
s=fresh();s.started=true;t.chooseRoadLane('player',4);t.resolveDrive({raw:1,total:3});assert.equal(s.roadLanes.player,0,'Failed control does not change lane');
s=fresh();s.phase='choice';s.started=true;t.renderChoice();t.renderSupportRoll();t.renderDriveRoll();assert(nodes.get('#playArea').innerHTML.includes('Наземный транспорт'));
console.log('PASS: Foundry import, magical item effects, per-actor checks and saves, separate two-seat turn, assistant ram restriction, crew HP/resistance/runes, split damage, ranged target geometry, deferred lane snapshots, UI render.');
